export type ThemePref = "system" | "light" | "dark";
export type LangPref = "id" | "en";

const THEME_KEY = "pos_cashier_theme";
const LANG_KEY = "pos_cashier_lang";

export function getTheme(): ThemePref {
  if (typeof window === "undefined") return "system";
  const v = localStorage.getItem(THEME_KEY);
  if (v === "light" || v === "dark" || v === "system") return v;
  return "system";
}

export function setTheme(theme: ThemePref): void {
  localStorage.setItem(THEME_KEY, theme);
  applyTheme(theme);
}

export function getLang(): LangPref {
  if (typeof window === "undefined") return "id";
  const v = localStorage.getItem(LANG_KEY);
  if (v === "en" || v === "id") return v;
  return "id";
}

export function setLang(lang: LangPref): void {
  localStorage.setItem(LANG_KEY, lang);
  if (typeof document !== "undefined") {
    document.documentElement.lang = lang;
  }
}

export function applyTheme(theme: ThemePref = getTheme()): void {
  if (typeof document === "undefined") return;
  const dark =
    theme === "dark" ||
    (theme !== "light" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);
  document.documentElement.classList.toggle("dark", dark);
  document.documentElement.classList.remove("light");
}

export function copy(lang: LangPref) {
  if (lang === "en") {
    return {
      brand: "Cashier",
      title: "Sign in",
      subtitle: "Sign in with your cashier account to continue to POS PIN.",
      username: "Username",
      password: "Password",
      usernamePlaceholder: "e.g. cashier",
      passwordPlaceholder: "Enter your password",
      showPassword: "Show",
      hidePassword: "Hide",
      showPasswordAria: "Show password",
      hidePasswordAria: "Hide password",
      submit: "Sign in",
      pending: "Signing in…",
      apiDown: "Cannot reach the API. Try again when online.",
      notCashier: "This account is not a cashier account.",
      invalidResponse: "Invalid login response. Try again.",
      settings: "Settings",
      theme: "Theme",
      language: "Language",
      themeSystem: "System",
      themeLight: "Light",
      themeDark: "Dark",
      pinTitle: "Cashier PIN",
      pinSoon: "POS PIN unlock comes in the next story. Menu stays locked.",
      pinEnrollHint: "Create a 6-digit POS PIN for this device (first unlock after sign-in).",
      pinUnlockHint: "Enter your 6-digit POS PIN to open the menu.",
      pinWrong: "Wrong PIN. Try again.",
      pinOfflineNoMaterial:
        "Cannot unlock offline. Sign in online first to enroll a PIN on this device.",
      pinOfflineBadge: "(Offline)",
      pinInputLabel: "PIN (pasteable)",
      pinPasteHint: "You can type or paste 6 digits here.",
      pinSubmit: "Start shift",
      menuTitle: "Menu",
      menuSoon: "Product catalog arrives in the next story. Cart stays locked.",
      menuLocalOnly: "Products are loaded from this device’s Local Database only.",
      catalogPull: "Pull catalog",
      catalogPulling: "Pulling…",
      catalogPulled: "Last pull",
      catalogEmpty: "Catalog is empty. Pull products while online.",
      catalogEmptyOffline: "Go online and pull the catalog first.",
      catalogPullFail: "Catalog pull failed. Showing the last local catalog if any.",
      catalogOffline: "Cannot pull catalog while offline.",
      catalogNeedLogin: "Sign in online again to pull the catalog.",
      catalogBlockedPrice: "Invalid price — cannot sell",
      stock: "Stock",
      cart: "Cart",
      cartEmpty: "Cart is empty.",
      pay: "Pay",
      total: "Total",
      cashPayment: "Cash payment",
      storeCredit: "Store credit",
      storeCreditBalance: "Store credit balance",
      cashTender: "Cash",
      coupon: "Coupon",
      couponInvalid: "Invalid coupon — sale can continue without it.",
      voucher: "Voucher",
      voucherInvalid: "Voucher not found or empty.",
      voucherOffline: "Apply a voucher when online.",
      promoDiscount: "Promotion",
      managerDiscount: "Manager discount",
      managerPin: "Manager PIN",
      managerPinNeed: "Enter the 6-digit manager PIN for an extra discount.",
      loyaltyPoints: "Points",
      loyaltyRedeem: "Redeem points",
      loyaltyDiscount: "Loyalty discount",
      loyaltyOffline: "Redeem points when online.",
      loyaltyInsufficient: "Not enough points.",
      tenderFailCustomer: "Store credit needs an attached customer.",
      tenderFailBalance: "Store credit is more than the customer balance.",
      tenderFailSum: "Tenders must add up to the total.",
      receiptHint: "Confirm the receipt to complete the sale.",
      confirmReceipt: "Confirm receipt",
      cancelCheckout: "Cancel",
      receiptSuccess: "Receipt OK — sale complete.",
      checkoutFail: "Could not start checkout.",
      receiptFail: "Could not complete the sale. Try again.",
      qtyUp: "Increase",
      qtyDown: "Decrease",
      removeLine: "Remove",
      hold: "Hold",
      parked: "Held",
      resumeHold: "Resume",
      discardHold: "Discard",
      parkFail: "Could not hold the cart.",
      resumeFail: "Could not resume the held cart.",
      resumeFailBusy: "Hold or clear the current cart first.",
      holdLineCount: "{count} items",
      offlineKeep: "Sales stay saved on this device.",
      stockOut: "Out of stock",
      unpackTitle: "Open pack?",
      unpackBody:
        "{pcsUnit} stock is empty. Open {fromQty} {packUnit} of “{name}” into {toQty} {pcsUnit}? Pack stock will decrease by {fromQty}.",
      unpackConfirm: "Open pack",
      unpackCancel: "Cancel",
      unpackFail: "Could not open the pack. Try again.",
      unpackPackFallback: "pack",
      unpackPcsFallback: "pcs",
      receipt: "Receipt",
      offlineMode: "Offline mode",
      waitingUpload: "Waiting to upload",
      synced: "Synced",
      syncFail: "Upload failed; sale stays complete locally and will retry.",
      voidTitle: "Void",
      voidHint: "Void a complete sale from today. Cancelled checkout is not a void.",
      voidEmpty: "No complete sales today.",
      voidAction: "Void",
      voided: "Voided",
      voidOk: "Sale voided. Stock returned on this device.",
      voidFail: "Could not void this sale.",
      voidNeedPin: "Manager PIN required.",
      voidPinEnroll: "Create a 6-digit manager PIN for voids on this device (must differ from the cashier PIN).",
      voidPinUnlock: "Enter the 6-digit manager PIN to void.",
      voidPinSame: "Manager PIN must be different from the cashier PIN.",
      voidPinCancel: "Back",
      txTitle: "Transactions",
      txHint: "Today’s complete sales. Void on this device, or return a synced sale while online.",
      txBack: "Back to list",
      txColTime: "Time",
      txColRef: "Ref",
      txColItems: "Items",
      txColCustomer: "Customer",
      txColPay: "Payment",
      txColStatus: "Status",
      txColActions: "Actions",
      txWalkIn: "Walk-in",
      txPaySplit: "Split",
      txDayTotal: "Today’s total (not voided)",
      returnTitle: "Return",
      returnHint: "Choose quantities and a stock decision. Return needs a connection.",
      returnLookup: "Find sale",
      returnSaleId: "Sale ID",
      returnReason: "Reason",
      returnReasonPh: "e.g. wrong item",
      returnQty: "Return qty",
      returnDecision: "Stock decision",
      returnResellable: "Resellable",
      returnDamaged: "Damaged",
      returnWarranty: "Warranty (no restock)",
      returnSubmit: "Take return",
      returnOk: "Return saved. Waiting for manager cash refund.",
      returnFail: "Could not return this sale.",
      returnOffline: "Return needs a connection. Void today’s local sales instead.",
      returnVoided: "This sale was voided — it cannot be returned.",
      returnWaitingRefund: "Waiting for manager refund on Dashboard.",
      returnExchange: "Exchange sale ID (optional)",
      returnRemaining: "remaining",
      returnAlready: "Already returned",
      dayClose: "Day close",
      dayCloseBack: "Back to menu",
      dayCloseSummary: "Day summary",
      dayCloseSalesTotal: "Sales total",
      dayCloseCash: "Cash summary",
      dayCloseTxCount: "Transactions",
      dayCloseSyncOk: "All complete sales are uploaded.",
      dayCloseSyncPending: "complete sales waiting to upload",
      dayCloseAckLabel:
        "I acknowledge {count} complete sale(s) are still waiting to upload. They will stay on this device for Sync after the next login.",
      dayCloseAckRequired: "Acknowledge unsynced sales before continuing.",
      dayCloseContinue: "Continue to report",
      dayCloseReport: "Today’s sales report",
      dayCloseEmpty: "No complete sales today.",
      dayCloseStatusDone: "Done",
      dayCloseConfirm: "Confirm day close",
      dayCloseConfirmHint: "This ends the POS session and returns to sign-in.",
      dayCloseShiftOpen: "Close the shift before finishing day close.",
      dayCloseShiftRequired: "Today has sales. Close a shift before day close.",
      dayCloseGoShift: "Go to shift",
      dayCloseShiftExpected: "Expected (shift)",
      dayCloseShiftCounted: "Counted (shift)",
      dayCloseShiftDiff: "Difference",
      dayCloseNoShifts: "No shift closed today.",
      loading: "Loading…",
      logout: "Sign out",
      customerAttach: "Attach customer",
      customerHide: "Hide customer search",
      customerDetach: "Remove customer",
      customerSearch: "Search customers",
      customerSearchPh: "Name, phone, or email",
      customerEmpty: "No cached customers. Create one or pull while online.",
      customerNew: "New customer",
      customerName: "Name",
      customerPhone: "Phone",
      customerEmail: "Email",
      customerCreate: "Save customer",
      customerCreateFail: "Name plus phone or email is required.",
      customerDupPhone: "That phone already exists — the new customer was still saved.",
      customerTitle: "Customers",
      customerHistory: "Purchase history",
      customerSpend: "Total spend",
      customerHistoryOffline: "Server history needs a connection. Local sales for this customer still show below.",
      customerNoHistory: "No sales for this customer yet.",
      customerReturned: "Return",
      customerVoided: "Voided",
      customerGroup: "Group",
      shiftTitle: "Shift",
      shiftOpen: "Open shift",
      shiftOpeningCash: "Opening cash (Rp)",
      shiftOpeningHint: "Enter the cash in the drawer to start selling.",
      shiftOpeningRequired: "Enter the starting cash in the drawer to open the shift.",
      shiftActive: "Shift is open.",
      shiftAlready: "A shift is already open on this register.",
      shiftNeedOpen: "Open a shift before Pay. Hold still works.",
      shiftOpenFail: "Could not open the shift.",
      shiftToMenu: "Go to menu",
      shiftCashIn: "Cash in",
      shiftCashOut: "Cash out",
      shiftCashAmount: "Amount (Rp)",
      shiftCashReason: "Reason",
      shiftCashFail: "Could not record cash in/out.",
      shiftExpected: "Expected cash",
      shiftOpening: "Opening",
      shiftCashSales: "Cash sales",
      shiftRefunds: "Cash refunds",
      shiftVoids: "Cash voids",
      shiftCounted: "Counted in drawer (Rp)",
      shiftDifference: "Difference",
      shiftClose: "Close shift",
      shiftCloseWarn:
        "Counted cash does not match expected. Close anyway? The difference will be recorded.",
      shiftCloseFail: "Could not close the shift.",
      shiftClosed: "Shift closed. Open a new one to keep selling.",
    };
  }
  return {
    brand: "Kasir",
    title: "Masuk",
    subtitle: "Masuk dengan akun kasir untuk lanjut ke PIN kasir.",
    username: "Username",
    password: "Password",
    usernamePlaceholder: "contoh: cashier",
    passwordPlaceholder: "Masukkan password",
    showPassword: "Tampil",
    hidePassword: "Sembunyi",
    showPasswordAria: "Tampilkan password",
    hidePasswordAria: "Sembunyikan password",
    submit: "Masuk",
    pending: "Memproses…",
    apiDown: "Tidak dapat menghubungi API. Coba lagi saat online.",
    notCashier: "Akun ini bukan akun kasir.",
    invalidResponse: "Respons login tidak valid. Coba lagi.",
    settings: "Pengaturan",
    theme: "Tema",
    language: "Bahasa",
    themeSystem: "Sistem",
    themeLight: "Terang",
    themeDark: "Gelap",
    pinTitle: "PIN kasir",
    pinSoon: "Buka kunci PIN kasir datang di story berikutnya. Menu masih terkunci.",
    pinEnrollHint:
      "Buat PIN kasir 6 digit untuk perangkat ini (buka kunci pertama setelah masuk).",
    pinUnlockHint: "Masukkan PIN kasir 6 digit untuk membuka menu.",
    pinWrong: "PIN salah. Coba lagi.",
    pinOfflineNoMaterial:
      "Tidak dapat buka kunci offline. Masuk online dulu untuk mendaftarkan PIN di perangkat ini.",
    pinOfflineBadge: "(Offline)",
    pinInputLabel: "PIN (bisa tempel)",
    pinPasteHint: "Ketik atau tempel 6 digit di sini.",
    pinSubmit: "Mulai shift",
    menuTitle: "Menu",
    menuSoon: "Katalog produk datang di story berikutnya. Keranjang masih terkunci.",
    menuLocalOnly: "Produk dibaca hanya dari Local Database perangkat ini.",
    catalogPull: "Tarik katalog",
    catalogPulling: "Menarik…",
    catalogPulled: "Tarik terakhir",
    catalogEmpty: "Katalog kosong. Tarik produk saat online.",
    catalogEmptyOffline: "Online dulu dan tarik katalog.",
    catalogPullFail: "Gagal tarik katalog. Menampilkan katalog lokal terakhir jika ada.",
    catalogOffline: "Tidak dapat tarik katalog saat offline.",
    catalogNeedLogin: "Masuk online lagi untuk menarik katalog.",
    catalogBlockedPrice: "Harga tidak valid — tidak bisa dijual",
    stock: "Stok",
    cart: "Keranjang",
    cartEmpty: "Keranjang kosong.",
    pay: "Bayar",
    total: "Total",
    cashPayment: "Pembayaran tunai",
    storeCredit: "Kredit toko",
    storeCreditBalance: "Saldo kredit toko",
    cashTender: "Tunai",
    coupon: "Kupon",
    couponInvalid: "Kupon tidak valid — penjualan bisa lanjut tanpa kupon.",
    voucher: "Voucher",
    voucherInvalid: "Voucher tidak ditemukan atau habis.",
    voucherOffline: "Pakai voucher saat online.",
    promoDiscount: "Promo",
    managerDiscount: "Diskon manajer",
    managerPin: "PIN manajer",
    managerPinNeed: "Masukkan PIN manajer 6 digit untuk diskon tambahan.",
    loyaltyPoints: "Poin",
    loyaltyRedeem: "Tukar poin",
    loyaltyDiscount: "Diskon loyalitas",
    loyaltyOffline: "Tukar poin saat online.",
    loyaltyInsufficient: "Poin tidak cukup.",
    tenderFailCustomer: "Kredit toko membutuhkan pelanggan.",
    tenderFailBalance: "Kredit toko melebihi saldo pelanggan.",
    tenderFailSum: "Jumlah tender harus sama dengan total.",
    receiptHint: "Konfirmasi struk untuk menyelesaikan penjualan.",
    confirmReceipt: "Konfirmasi struk",
    cancelCheckout: "Batal",
    receiptSuccess: "Struk berhasil — penjualan selesai.",
    checkoutFail: "Tidak dapat memulai pembayaran.",
    receiptFail: "Tidak dapat menyelesaikan penjualan. Coba lagi.",
    qtyUp: "Tambah",
    qtyDown: "Kurangi",
    removeLine: "Hapus",
    hold: "Tahan",
    parked: "Ditahan",
    resumeHold: "Lanjutkan",
    discardHold: "Buang",
    parkFail: "Tidak dapat menahan keranjang.",
    resumeFail: "Tidak dapat melanjutkan keranjang ditahan.",
    resumeFailBusy: "Tahan atau kosongkan keranjang saat ini dulu.",
    holdLineCount: "{count} item",
    offlineKeep: "Penjualan tetap tersimpan di perangkat ini.",
    stockOut: "Stok habis",
    unpackTitle: "Buka kemasan?",
    unpackBody:
      "Stok {pcsUnit} habis. Buka {fromQty} {packUnit} “{name}” menjadi {toQty} {pcsUnit}? Stok kemasan berkurang {fromQty}.",
    unpackConfirm: "Buka kemasan",
    unpackCancel: "Batal",
    unpackFail: "Tidak dapat membuka kemasan. Coba lagi.",
    unpackPackFallback: "Pack",
    unpackPcsFallback: "pcs",
    receipt: "Struk",
    offlineMode: "Mode offline",
    waitingUpload: "Menunggu unggah",
    synced: "Tersinkron",
    syncFail: "Unggah gagal; penjualan tetap selesai di lokal dan akan dicoba lagi.",
    voidTitle: "Void",
    voidHint: "Void penjualan selesai hari ini. Batal checkout bukan void.",
    voidEmpty: "Belum ada penjualan selesai hari ini.",
    voidAction: "Void",
    voided: "Di-void",
    voidOk: "Penjualan di-void. Stok dikembalikan di perangkat ini.",
    voidFail: "Tidak dapat void penjualan ini.",
    voidNeedPin: "PIN manajer diperlukan.",
    voidPinEnroll:
      "Buat PIN manajer 6 digit untuk void di perangkat ini (harus berbeda dari PIN kasir).",
    voidPinUnlock: "Masukkan PIN manajer 6 digit untuk void.",
    voidPinSame: "PIN manajer harus berbeda dari PIN kasir.",
    voidPinCancel: "Kembali",
    txTitle: "Transaksi",
    txHint: "Penjualan selesai hari ini. Void di perangkat, atau retur penjualan tersinkron saat online.",
    txBack: "Kembali ke daftar",
    txColTime: "Waktu",
    txColRef: "Ref",
    txColItems: "Produk",
    txColCustomer: "Pelanggan",
    txColPay: "Bayar",
    txColStatus: "Status",
    txColActions: "Aksi",
    txWalkIn: "Tanpa pelanggan",
    txPaySplit: "Campuran",
    txDayTotal: "Total hari ini (bukan void)",
    returnTitle: "Retur",
    returnHint: "Pilih jumlah dan keputusan stok. Retur perlu koneksi.",
    returnLookup: "Cari penjualan",
    returnSaleId: "ID penjualan",
    returnReason: "Alasan",
    returnReasonPh: "contoh: salah barang",
    returnQty: "Qty retur",
    returnDecision: "Keputusan stok",
    returnResellable: "Layak jual",
    returnDamaged: "Rusak",
    returnWarranty: "Garansi (tidak restok)",
    returnSubmit: "Terima retur",
    returnOk: "Retur tersimpan. Menunggu refund tunai manajer.",
    returnFail: "Tidak dapat retur penjualan ini.",
    returnOffline: "Retur perlu koneksi. Void penjualan lokal hari ini sebagai gantinya.",
    returnVoided: "Penjualan ini sudah di-void — tidak dapat di-return.",
    returnWaitingRefund: "Menunggu refund manajer di Dashboard.",
    returnExchange: "ID penjualan tukar (opsional)",
    returnRemaining: "sisa",
    returnAlready: "Sudah di-return",
    dayClose: "Tutup hari",
    dayCloseBack: "Kembali ke menu",
    dayCloseSummary: "Ringkasan hari",
    dayCloseSalesTotal: "Total penjualan",
    dayCloseCash: "Ringkasan tunai",
    dayCloseTxCount: "Transaksi",
    dayCloseSyncOk: "Semua penjualan selesai sudah diunggah.",
    dayCloseSyncPending: "penjualan selesai menunggu unggah",
    dayCloseAckLabel:
      "Saya memahami ada {count} penjualan selesai yang masih menunggu unggah. Data tetap di perangkat ini untuk Sync setelah login berikutnya.",
    dayCloseAckRequired: "Centang pengakuan sebelum melanjutkan.",
    dayCloseContinue: "Lanjut ke laporan",
    dayCloseReport: "Laporan penjualan hari ini",
    dayCloseEmpty: "Belum ada penjualan selesai hari ini.",
    dayCloseStatusDone: "Selesai",
    dayCloseConfirm: "Konfirmasi tutup hari",
    dayCloseConfirmHint: "Ini mengakhiri sesi POS dan kembali ke layar masuk.",
    dayCloseShiftOpen: "Tutup shift dulu sebelum tutup hari.",
    dayCloseShiftRequired: "Ada penjualan hari ini. Tutup shift dulu sebelum tutup hari.",
    dayCloseGoShift: "Ke shift",
    dayCloseShiftExpected: "Diharapkan (shift)",
    dayCloseShiftCounted: "Dihitung (shift)",
    dayCloseShiftDiff: "Selisih",
    dayCloseNoShifts: "Belum ada shift tertutup hari ini.",
    loading: "Memuat…",
    logout: "Keluar",
    customerAttach: "Lampirkan pelanggan",
    customerHide: "Sembunyikan cari pelanggan",
    customerDetach: "Lepas pelanggan",
    customerSearch: "Cari pelanggan",
    customerSearchPh: "Nama, telepon, atau email",
    customerEmpty: "Belum ada pelanggan di cache. Buat baru atau tarik saat online.",
    customerNew: "Pelanggan baru",
    customerName: "Nama",
    customerPhone: "Telepon",
    customerEmail: "Email",
    customerCreate: "Simpan pelanggan",
    customerCreateFail: "Nama plus telepon atau email wajib.",
    customerDupPhone: "Nomor telepon sudah ada — pelanggan baru tetap disimpan.",
    customerTitle: "Pelanggan",
    customerHistory: "Riwayat belanja",
    customerSpend: "Total belanja",
    customerHistoryOffline:
      "Riwayat server butuh koneksi. Penjualan lokal pelanggan ini tetap tampil di bawah.",
    customerNoHistory: "Belum ada penjualan untuk pelanggan ini.",
    customerReturned: "Retur",
    customerVoided: "Di-void",
    customerGroup: "Grup",
    shiftTitle: "Shift",
    shiftOpen: "Buka shift",
    shiftOpeningCash: "Kas awal (Rp)",
    shiftOpeningHint: "Masukkan uang di laci untuk mulai menjual.",
    shiftOpeningRequired: "Masukkan kas awal di laci untuk membuka shift.",
    shiftActive: "Shift sedang terbuka.",
    shiftAlready: "Shift masih terbuka di register ini.",
    shiftNeedOpen: "Buka shift dulu sebelum Bayar. Tahan tetap bisa.",
    shiftOpenFail: "Tidak dapat membuka shift.",
    shiftToMenu: "Ke menu",
    shiftCashIn: "Kas masuk",
    shiftCashOut: "Kas keluar",
    shiftCashAmount: "Jumlah (Rp)",
    shiftCashReason: "Alasan",
    shiftCashFail: "Tidak dapat mencatat kas masuk/keluar.",
    shiftExpected: "Kas diharapkan",
    shiftOpening: "Kas awal",
    shiftCashSales: "Penjualan tunai",
    shiftRefunds: "Refund tunai",
    shiftVoids: "Void tunai",
    shiftCounted: "Hitungan laci (Rp)",
    shiftDifference: "Selisih",
    shiftClose: "Tutup shift",
    shiftCloseWarn:
      "Hitungan laci tidak sama dengan kas diharapkan. Tetap tutup? Selisih akan dicatat.",
    shiftCloseFail: "Tidak dapat menutup shift.",
    shiftClosed: "Shift ditutup. Buka yang baru untuk lanjut menjual.",
  };
}
